version: '2'
services:
  dynamomigrationtest-app:
    image: dynamomigrationtest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=dynamomigrationtest-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  dynamomigrationtest-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: dynamomigrationtest-cassandra
  dynamomigrationtest-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=dynamomigrationtest-cassandra
  dynamomigrationtest-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: dynamomigrationtest-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
