version: '2'
services:
  dynamomigrationtest-cassandra:
    image: cassandra:3.11.5
    # volumes:
    #     - ~/volumes/jhipster/DynamoMigrationTest/cassandra/:/var/lib/cassandra/data
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
  dynamomigrationtest-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: dynamomigrationtest-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace.cql
